apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-quest-pv-claim
  namespace: quests-staging-svc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
