apiVersion: v1
kind: Service
metadata:
  name: laravel-api
  #namespace: laravel
spec:
  ports:
  - name: pat-api-port
    port: 80
    targetPort: pathao-port
  selector:
    app: laravel-app
  type: LoadBalancer
