#FROM php:7.1.3-fpm
FROM php:7.2-fpm
MAINTAINER < Haryono | onoy - haryonoaryo351@gmail.com >
LABEL maintainer="poskota"

# Install PHP extensions and PECL modules.
RUN buildDeps=" \
        default-libmysqlclient-dev \
        libbz2-dev \
        libmemcached-dev \
        libsasl2-dev \
    " \
    runtimeDeps=" \
        curl \
        git \
        libfreetype6-dev \
        libicu-dev \
        libjpeg-dev \
        libldap2-dev \
        libmemcachedutil2 \
        libpng-dev \
        libpq-dev \
        libxml2-dev \
    " \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y $buildDeps $runtimeDeps \
    && docker-php-ext-install bcmath bz2 calendar iconv intl mbstring mysqli opcache pdo_mysql pdo_pgsql pgsql soap zip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-install ldap \
    && docker-php-ext-install exif \
    && pecl install memcached redis \
    && docker-php-ext-enable memcached.so redis.so \
    && apt-get purge -y --auto-remove $buildDeps \
    && rm -r /var/lib/apt/lists/*

# Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && ln -s $(composer config --global home) /root/composer
ENV PATH=$PATH:/root/composer/vendor/bin COMPOSER_ALLOW_SUPERUSER=1


#====================================
RUN apt-get update -y
RUN apt-get install nano -y
RUN apt-get install ntp -y
RUN rm -f /etc/localtime;  ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
RUN apt-get install supervisor -y
	
RUN apt-get install -y nginx  && \
    rm -rf /var/lib/apt/lists/*


COPY . /var/www/html
RUN mv /root/.composer/auth.json /root/.composer/auth.json-bak
COPY ./deploy/auth.json /root/.composer/
WORKDIR /var/www/html

RUN rm /etc/nginx/sites-enabled/default
COPY ./deploy/deploy.conf /etc/nginx/conf.d/default.conf
RUN mv /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf.backup
COPY ./deploy/www.conf /usr/local/etc/php-fpm.d/www.conf
RUN usermod -a -G www-data root
RUN chgrp -R www-data storage
RUN chown -R www-data:www-data ./storage
RUN chmod -R 0777 ./storage
COPY ./deploy/start-backend.sh /root/
#=====CONJOB ZONE
RUN apt-get update -y
RUN apt-get -y install cron

COPY ./deploy/crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN touch /var/log/cron.log
RUN ln -s ./secret/.env .env

RUN chmod +x ./deploy/run

ENTRYPOINT ["./deploy/run"]
EXPOSE 80
#RUN /usr/local/bin/php -S php -S 0.0.0.0:80 -t /var/www/html index.php > log-backend.log 2>&1 &
